---

before_install:
  - "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  - "sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\""
  - "sudo apt-get update"
  - "sudo apt-get -y install docker-ce"
branches:
  only:
    - "master"
env:
  global:
    - "IMAGE=irap/docker-debian-ansible:stretch"
  matrix:
    - "ANSIBLE_VERSION=2.4.3.0"
    - "ANSIBLE_VERSION=2.3.3.0"
    - "ANSIBLE_VERSION=2.2.3.0"
language: "python"
notifications:
  email: false
python:
  - "2.7"
script:
  - "wget -O ${PWD}/run.sh https://raw.githubusercontent.com/pari-/docker-debian-ansible/master/run.sh"
  - "chmod +x ${PWD}/run.sh"
  - "${PWD}/run.sh"
services: "docker"
sudo: "required"
